## **Ecoding - Converting Categorical into Numerical**


### **Two methods - LabelEncoder and OneHotEncoder**

**1)Label Encoding**

In [24]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [25]:
le = LabelEncoder()

In [26]:
df = pd.read_csv("/content/customer_churn_dataset-training-master.csv")

In [27]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [28]:
df["Gender"] = le.fit_transform(df["Gender"])

In [29]:
df["Gender"]

0         0
1         0
2         0
3         1
4         1
         ..
440828    1
440829    0
440830    1
440831    1
440832    1
Name: Gender, Length: 440833, dtype: int64

**2)One Hot Encoder**

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
ohe = OneHotEncoder()

In [32]:
S_T = ohe.fit_transform(df[["Subscription Type"]])